'use client'

import { Link } from 'wouter'
import { Shield, Lock, Server, Scale } from 'lucide-react'

export default function DataProcessing() {
  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans selection:bg-indigo-100 selection:text-indigo-900">
      {/* Simple Nav */}
      <nav className="border-b border-gray-100 sticky top-0 bg-white/80 backdrop-blur-md z-50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="text-xl font-serif font-medium tracking-tight hover:opacity-70 transition-opacity">
            synth<span className="text-indigo-600">.ai</span>
          </Link>
          <Link href="/terms" className="text-sm font-medium text-gray-500 hover:text-gray-900 transition-colors">
            Terms of Use
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-20">
        <header className="mb-20">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-50 text-green-700 text-xs font-bold uppercase tracking-widest mb-6">
            <Shield className="w-3 h-3" />
            Security First
          </div>
          <h1 className="text-5xl md:text-6xl font-serif font-medium tracking-tight text-gray-900 mb-6">
            Data Processing Policy
          </h1>
          <p className="text-xl text-gray-500 font-medium">Last updated: July 2026</p>
        </header>

        <div className="prose prose-gray prose-lg max-w-none">
          <section className="mb-16">
            <h2 className="text-3xl font-serif font-medium text-gray-900 mb-8">1. Introduction</h2>
            <p className="text-gray-600 leading-relaxed">
              Synth AI (“Synth,” “we,” “us,” or “our”) provides an autonomous AI agent platform that helps regulated enterprises automate operational workflows. We are committed to protecting the privacy and security of the data our customers (“you” or “your”) entrust to us.
            </p>
            <p className="text-gray-600 leading-relaxed">
              This Data Processing Policy explains what data we process, why, where it is stored, and — critically — how our architectural choices ensure that your proprietary business knowledge remains yours alone.
            </p>
          </section>

          <section className="mb-16 grid md:grid-cols-2 gap-8 not-prose">
            <div className="p-8 bg-gray-50 rounded-[32px] border border-gray-100">
              <h3 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                <UserCircle className="w-5 h-5 text-indigo-600" /> You are the Data Controller
              </h3>
              <p className="text-gray-500 text-sm leading-relaxed">
                You determine the purposes and means of processing your data.
              </p>
            </div>
            <div className="p-8 bg-indigo-50 rounded-[32px] border border-indigo-100">
              <h3 className="text-lg font-bold text-indigo-900 mb-4 flex items-center gap-2">
                <Shield className="w-5 h-5 text-indigo-600" /> Synth is the Data Processor
              </h3>
              <p className="text-indigo-900/70 text-sm leading-relaxed">
                We process data only on your documented instructions, as set out in our service agreement and this policy.
              </p>
            </div>
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-serif font-medium text-gray-900 mb-8">2. Data We Process</h2>
            <div className="space-y-6">
              {[
                { title: 'Account data', desc: 'Names, email addresses, and contact details of authorised users.' },
                { title: 'Operational data', desc: 'Workflows, configurations, and logs generated by your use of the platform.' },
                { title: 'Content data', desc: 'Text of documents, messages, and information you instruct the agent to process.' },
                { title: 'Metadata', desc: 'Timestamps and performance metrics necessary for auditing and reliability.' }
              ].map((item, i) => (
                <div key={i} className="flex gap-4 p-6 border border-gray-100 rounded-2xl hover:border-indigo-100 transition-colors">
                  <div className="w-2 h-2 rounded-full bg-indigo-600 mt-2 flex-shrink-0" />
                  <div>
                    <h4 className="font-bold text-gray-900 mb-1">{item.title}</h4>
                    <p className="text-gray-500 text-sm">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="mb-16 bg-gray-900 text-white rounded-[40px] p-10 md:p-16 overflow-hidden relative">
            <div className="relative z-10">
              <h2 className="text-3xl md:text-4xl font-serif font-medium mb-8">
                Protecting Your Competitive Edge
              </h2>
              <div className="space-y-8 max-w-2xl">
                <div>
                  <h3 className="text-indigo-400 font-bold mb-2">Why Open-Source Models?</h3>
                  <p className="text-gray-400 leading-relaxed">
                    Most AI platforms use proprietary, closed-source models. When you send data to them, you risk sharing proprietary domain expertise with a third party.
                  </p>
                </div>
                <div className="grid md:grid-cols-2 gap-6">
                  <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                    <h4 className="font-bold mb-2">Self-Hosted</h4>
                    <p className="text-xs text-gray-500">Models run on your side of the fence. No data ever flows back to a central provider.</p>
                  </div>
                  <div className="p-6 bg-white/5 rounded-2xl border border-white/10">
                    <h4 className="font-bold mb-2">No Training</h4>
                    <p className="text-xs text-gray-500">Models are static. They do not learn from your data, protecting your "alpha".</p>
                  </div>
                </div>
              </div>
            </div>
            <div className="absolute -right-20 -bottom-20 w-80 h-80 bg-indigo-600/20 rounded-full blur-[100px]" />
          </section>

          <section className="mb-16">
            <h2 className="text-3xl font-serif font-medium text-gray-900 mb-8">Infrastructure & Security</h2>
            <div className="grid md:grid-cols-3 gap-6 not-prose">
              <div className="p-6 border border-gray-100 rounded-2xl">
                <Server className="w-8 h-8 text-gray-400 mb-4" />
                <h4 className="font-bold mb-2">AWS Infrastructure</h4>
                <p className="text-xs text-gray-500">Stored in regions selected by you at deployment time.</p>
              </div>
              <div className="p-6 border border-gray-100 rounded-2xl">
                <Lock className="w-8 h-8 text-gray-400 mb-4" />
                <h4 className="font-bold mb-2">Encryption</h4>
                <p className="text-xs text-gray-500">AES-256 at rest and TLS 1.2+ in transit for all data.</p>
              </div>
              <div className="p-6 border border-gray-100 rounded-2xl">
                <Scale className="w-8 h-8 text-gray-400 mb-4" />
                <h4 className="font-bold mb-2">POPIA Compliant</h4>
                <p className="text-xs text-gray-500">Full compliance with South African data protection laws.</p>
              </div>
            </div>
          </section>

          <section className="mb-16 bg-indigo-50 rounded-[32px] p-10 border border-indigo-100">
            <h2 className="text-2xl font-serif font-medium text-indigo-900 mb-4">Questions?</h2>
            <p className="text-indigo-900/70 mb-8">
              If you have questions about this Data Processing Policy or wish to exercise your rights, please contact our Information Officer.
            </p>
            <div className="space-y-2">
              <p className="font-bold text-indigo-900">Synth AI (Pty) Ltd</p>
              <a href="mailto:privacy@synth.ai" className="text-indigo-600 font-bold hover:underline">
                privacy@synth.ai
              </a>
              <p className="text-sm text-indigo-900/50 mt-4">Cape Town, South Africa</p>
            </div>
          </section>
        </div>
      </main>

      <footer className="border-t border-gray-100 py-12">
        <div className="max-w-4xl mx-auto px-6 flex justify-between items-center text-sm text-gray-400">
          <p>© 2026 Synth AI (Pty) Ltd.</p>
          <div className="flex gap-6">
            <Link href="/terms" className="hover:text-gray-900 transition-colors">Terms</Link>
            <a href="mailto:privacy@synth.ai" className="hover:text-gray-900 transition-colors">Privacy</a>
          </div>
        </div>
      </footer>
    </div>
  )
}

function UserCircle(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662" />
    </svg>
  )
}